export const mockCategories = [
    {
      _id: "cat1",
      name: "Laptops",
      category_name: "Laptops",
      category_type: "hardware",
      total_assets: 10,
      assigned_assets: 5,
      under_maintenance: 1,
      total_cost: 10000,
      is_allotted: false,
    },
    {
      _id: "cat2",
      name: "Stationery",
      category_name: "Stationery",
      category_type: "stationery",
      total_assets: 50,
      assigned_assets: 20,
      under_maintenance: 0,
      total_cost: 500,
      is_allotted: true,
    },
  ];
  
  export const mockAssets = [
    {
      _id: "asset1",
      category_id: "cat1",
      asset_tag: "LAP001",
      name: "Dell XPS 13",
      serial_number: "SN123456",
      status: "assigned",
      purchase_cost: 1500,
      specifications: { CPU: "Intel i7", RAM: "16GB", Storage: "512GB SSD" },
      has_active_assignment: true,
      current_assignment_date: "2025-01-15T00:00:00Z",
      current_assignee_id: "emp1",
      is_operational: true,
      condition: "Good",
      created_at: "2024-12-01T00:00:00Z",
      updated_at: "2025-01-15T00:00:00Z",
      model: "XPS 13",
      vendor: "Dell",
      purchase_date: "2024-12-01",
      warranty_until: "2026-12-01",
      current_value: 1200,
      notes: "Company-issued laptop",
      insurance_policy: "POL123",
      disposal_date: null,
      maintenance_due_date: "2025-12-01",
    },
    {
      _id: "asset2",
      category_id: "cat1",
      asset_tag: "LAP002",
      name: "MacBook Pro",
      serial_number: "SN789012",
      status: "available",
      purchase_cost: 2000,
      specifications: { CPU: "M1 Pro", RAM: "32GB", Storage: "1TB SSD" },
      has_active_assignment: false,
      current_assignment_date: null,
      current_assignee_id: null,
      is_operational: true,
      condition: "Excellent",
      created_at: "2024-11-01T00:00:00Z",
      updated_at: "2024-11-01T00:00:00Z",
      model: "MacBook Pro 14",
      vendor: "Apple",
      purchase_date: "2024-11-01",
      warranty_until: "2027-11-01",
      current_value: 1800,
      notes: "In storage",
      insurance_policy: "POL456",
      disposal_date: null,
      maintenance_due_date: "2025-11-01",
    },
    {
      _id: "asset3",
      category_id: "cat2",
      asset_tag: "STA001",
      name: "Ballpoint Pen Set",
      serial_number: "SN345678",
      status: "assigned",
      purchase_cost: 10,
      specifications: { Color: "Blue", Quantity: "100" },
      has_active_assignment: true,
      current_assignment_date: "2025-02-01T00:00:00Z",
      current_assignee_id: "emp2",
      is_operational: true,
      condition: "New",
      created_at: "2025-01-01T00:00:00Z",
      updated_at: "2025-02-01T00:00:00Z",
      model: "Basic Pen",
      vendor: "Stationery Inc.",
      purchase_date: "2025-01-01",
      warranty_until: null,
      current_value: 8,
      notes: "Bulk stationery",
      insurance_policy: null,
      disposal_date: null,
      maintenance_due_date: null,
    },
  ];
  
  export const mockAssignmentHistory = [
    {
      id: "assign1",
      asset_id: "asset1",
      assigned_to: "emp1",
      entity_type: "employee",
      department: "Engineering",
      condition_at_assignment: "Good",
      assigned_at: "2025-01-15",
      unassigned_at: null,
      is_active: true,
      notes: "Assigned to John Doe",
    },
    {
      id: "assign2",
      asset_id: "asset1",
      assigned_to: "emp2",
      entity_type: "employee",
      department: "HR",
      condition_at_assignment: "Good",
      assigned_at: "2024-12-01",
      unassigned_at: "2025-01-14",
      is_active: false,
      notes: "Returned due to upgrade",
    },
    {
      id: "assign3",
      asset_id: "asset3",
      assigned_to: "emp2",
      entity_type: "employee",
      department: "HR",
      condition_at_assignment: "New",
      assigned_at: "2025-02-01",
      unassigned_at: null,
      is_active: true,
      notes: "Assigned to Jane Smith",
    },
  ];
  
  export const mockMaintenanceHistory = [
    {
      id: "maint1",
      asset_id: "asset1",
      maintenance_type: "Hardware Upgrade",
      technician: "Tech One",
      condition_before: "Good",
      condition_after: "Excellent",
      maintenance_date: "2025-03-01",
      completed_date: "2025-03-02",
      cost: 200,
      status: "completed",
      notes: "Upgraded RAM to 32GB",
    },
    {
      id: "maint2",
      asset_id: "asset2",
      maintenance_type: "Cleaning",
      technician: "Tech Two",
      condition_before: "Excellent",
      condition_after: "Excellent",
      maintenance_date: "2025-04-01",
      completed_date: null,
      cost: 50,
      status: "pending",
      notes: "Scheduled cleaning",
    },
  ];
  
  export const mockDocuments = [
    {
      id: "doc1",
      asset_id: "asset1",
      file_url: "/documents/asset1/receipt.pdf",
      document_type: "Purchase Receipt",
      created_at: "2024-12-01",
      file_size: 102400, // 100 KB
    },
    {
      id: "doc2",
      asset_id: "asset1",
      file_url: "/documents/asset1/warranty.pdf",
      document_type: "Warranty",
      created_at: "2024-12-01",
      file_size: 204800, // 200 KB
    },
  ];
  
  export const mockEmployees = [
    {
      _id: "emp1",
      first_name: "John",
      last_name: "Doe",
      department: "Engineering",
    },
    {
      _id: "emp2",
      first_name: "Jane",
      last_name: "Smith",
      department: "HR",
    },
  ];